title: Learning Python
author: Lety
description: >-
  Learning and trying to undestand the Python language. 
intro: >-
  Welcome to my blog.
github_username: siuatl

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

theme: "minima"

rss: rss

plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      tags: Other
